name: SurvivalGamesV4
main: SurvivalGamesV4\SurvivalGamesV4
version: 4.0.1.8
api: [1.0.0, 2.0.0, 3.0.0]
author: ImagicalGamer


commands:
    sg:
        usage: /sg
        description: A full list of SurvivalGames-Commands
    setrank:
        usage: /setrank
        description: Rank-Commands
